KerasJson: ../../../RFNoC-HLS-NeuralNet/rfnoc/hls4ml/keras-to-hls/example-keras-model-files/KERAS_conv2d_model.json
KerasH5:   ../../../RFNoC-HLS-NeuralNet/rfnoc/hls4ml/keras-to-hls/example-keras-model-files/KERAS_conv2d_model_weights.h5

######## try list
#KerasJson: ../../hls4ml/keras-to-hls/example-keras-model-files/jetTagger_Conv2D_Small.json
#KerasH5:   ../../hls4ml/keras-to-hls/example-keras-model-files/jetTagger_Conv2D_Small.h5

######## OK 
#KerasJson: ../../hls4ml/keras-to-hls/example-keras-model-files/KERAS_conv1d_small.json
#KerasH5:   ../../hls4ml/keras-to-hls/example-keras-model-files/KERAS_conv1d_small_weights.h5

#KerasJson: ../../hls4ml/keras-to-hls/example-keras-model-files/KERAS_dense_big.json
#KerasH5:   ../../hls4ml/keras-to-hls/example-keras-model-files/KERAS_dense_big_weights.h5

OutputDir: ./
ProjectName: cnn_sample
XilinxPart: xcku115-flvb2104-2-i
#XilinxPart: xc7z020clg484-1

ClockPeriod: 5
IOType: io_parallel
#IOType: io_parallel / io_serial
Strategy: Resource
#Strategy: Latency
ReuseFactor: 128
DefaultPrecision: ap_fixed<8,6>
#DefaultPrecision: ap_fixed<16,6>
